//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceConsumption.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SampleWebserviceSoap")]
    public interface SampleWebserviceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceConsumption.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceConsumption.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceConsumption.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculation", ReplyAction="*")]
        WebServiceConsumption.ServiceReference1.calculationResponse calculation(WebServiceConsumption.ServiceReference1.calculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.calculationResponse> calculationAsync(WebServiceConsumption.ServiceReference1.calculationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceConsumption.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceConsumption.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceConsumption.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceConsumption.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculation", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceConsumption.ServiceReference1.calculationRequestBody Body;
        
        public calculationRequest() {
        }
        
        public calculationRequest(WebServiceConsumption.ServiceReference1.calculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class calculationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public calculationRequestBody() {
        }
        
        public calculationRequestBody(int firstvalue, int secondvalue, string operation) {
            this.firstvalue = firstvalue;
            this.secondvalue = secondvalue;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceConsumption.ServiceReference1.calculationResponseBody Body;
        
        public calculationResponse() {
        }
        
        public calculationResponse(WebServiceConsumption.ServiceReference1.calculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class calculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string calculationResult;
        
        public calculationResponseBody() {
        }
        
        public calculationResponseBody(string calculationResult) {
            this.calculationResult = calculationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleWebserviceSoapChannel : WebServiceConsumption.ServiceReference1.SampleWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebserviceSoapClient : System.ServiceModel.ClientBase<WebServiceConsumption.ServiceReference1.SampleWebserviceSoap>, WebServiceConsumption.ServiceReference1.SampleWebserviceSoap {
        
        public SampleWebserviceSoapClient() {
        }
        
        public SampleWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceConsumption.ServiceReference1.HelloWorldResponse WebServiceConsumption.ServiceReference1.SampleWebserviceSoap.HelloWorld(WebServiceConsumption.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceConsumption.ServiceReference1.HelloWorldRequest inValue = new WebServiceConsumption.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceConsumption.ServiceReference1.HelloWorldRequestBody();
            WebServiceConsumption.ServiceReference1.HelloWorldResponse retVal = ((WebServiceConsumption.ServiceReference1.SampleWebserviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.HelloWorldResponse> WebServiceConsumption.ServiceReference1.SampleWebserviceSoap.HelloWorldAsync(WebServiceConsumption.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServiceConsumption.ServiceReference1.HelloWorldRequest inValue = new WebServiceConsumption.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceConsumption.ServiceReference1.HelloWorldRequestBody();
            return ((WebServiceConsumption.ServiceReference1.SampleWebserviceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceConsumption.ServiceReference1.calculationResponse WebServiceConsumption.ServiceReference1.SampleWebserviceSoap.calculation(WebServiceConsumption.ServiceReference1.calculationRequest request) {
            return base.Channel.calculation(request);
        }
        
        public string calculation(int firstvalue, int secondvalue, string operation) {
            WebServiceConsumption.ServiceReference1.calculationRequest inValue = new WebServiceConsumption.ServiceReference1.calculationRequest();
            inValue.Body = new WebServiceConsumption.ServiceReference1.calculationRequestBody();
            inValue.Body.firstvalue = firstvalue;
            inValue.Body.secondvalue = secondvalue;
            inValue.Body.operation = operation;
            WebServiceConsumption.ServiceReference1.calculationResponse retVal = ((WebServiceConsumption.ServiceReference1.SampleWebserviceSoap)(this)).calculation(inValue);
            return retVal.Body.calculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.calculationResponse> WebServiceConsumption.ServiceReference1.SampleWebserviceSoap.calculationAsync(WebServiceConsumption.ServiceReference1.calculationRequest request) {
            return base.Channel.calculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceConsumption.ServiceReference1.calculationResponse> calculationAsync(int firstvalue, int secondvalue, string operation) {
            WebServiceConsumption.ServiceReference1.calculationRequest inValue = new WebServiceConsumption.ServiceReference1.calculationRequest();
            inValue.Body = new WebServiceConsumption.ServiceReference1.calculationRequestBody();
            inValue.Body.firstvalue = firstvalue;
            inValue.Body.secondvalue = secondvalue;
            inValue.Body.operation = operation;
            return ((WebServiceConsumption.ServiceReference1.SampleWebserviceSoap)(this)).calculationAsync(inValue);
        }
    }
}
