<%@ Page Title="" Language="C#" MasterPageFile="~/NavNmaster/master.Master" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="CsharpWebApp.NavNmaster.home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
    <br />
    Home:</p>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    State governments set overall educational standards, often mandate<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Standardized_testing" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Standardized testing">standardized tests</a><span>&nbsp;</span>for<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/K–12" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="K–12">K–12</a><span>&nbsp;</span>public school systems and supervise, usually through a board of regents, state colleges and universities. Funding comes from the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/State_law_(United_States)" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="State law (United States)">state</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Local_government_in_the_United_States" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Local government in the United States">local</a>, 
    and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Federal_government_of_the_United_States" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Federal government of the United States">federal</a><span>&nbsp;</span>government.<sup id="cite_ref-[142]_4-0" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-size: 11.2px; font-weight: normal; font-style: normal;"><a href="https://en.wikipedia.org/wiki/Education_in_the_United_States#cite_note-[142]-4" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[4]</a></sup><span>&nbsp;</span>Private schools are generally free to determine their own curriculum and staffing policies, with voluntary accreditation available through independent regional accreditation authorities, although some state regulation can apply.</p>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    In 2013, about 87% of school-age children (those below<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Higher_education" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Higher education">higher education</a>) attended state funded public schools, about 10% attended tuition- and foundation-funded private schools<sup id="cite_ref-5" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-size: 11.2px; font-weight: normal; font-style: normal;"><a href="https://en.wikipedia.org/wiki/Education_in_the_United_States#cite_note-5" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[5]</a></sup><span>&nbsp;</span>and roughly 3% were home-schooled.<sup id="cite_ref-6" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-size: 11.2px; font-weight: normal; font-style: normal;"><a href="https://en.wikipedia.org/wiki/Education_in_the_United_States#cite_note-6" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[6]</a></sup></p>
<p>
</p>


</p>
</asp:Content>
