//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jquery.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmpFirstName {
            get {
                return this.EmpFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpFirstNameField, value) != true)) {
                    this.EmpFirstNameField = value;
                    this.RaisePropertyChanged("EmpFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmpLastName {
            get {
                return this.EmpLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpLastNameField, value) != true)) {
                    this.EmpLastNameField = value;
                    this.RaisePropertyChanged("EmpLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.samplewebserviceSoap")]
    public interface samplewebserviceSoap {
        
        // CODEGEN: Generating message contract since element name GetEmployeeDetailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDetail", ReplyAction="*")]
        Jquery.ServiceReference1.GetEmployeeDetailResponse GetEmployeeDetail(Jquery.ServiceReference1.GetEmployeeDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Jquery.ServiceReference1.GetEmployeeDetailResponse> GetEmployeeDetailAsync(Jquery.ServiceReference1.GetEmployeeDetailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetail", Namespace="http://tempuri.org/", Order=0)]
        public Jquery.ServiceReference1.GetEmployeeDetailRequestBody Body;
        
        public GetEmployeeDetailRequest() {
        }
        
        public GetEmployeeDetailRequest(Jquery.ServiceReference1.GetEmployeeDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeDetailRequestBody {
        
        public GetEmployeeDetailRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public Jquery.ServiceReference1.GetEmployeeDetailResponseBody Body;
        
        public GetEmployeeDetailResponse() {
        }
        
        public GetEmployeeDetailResponse(Jquery.ServiceReference1.GetEmployeeDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Jquery.ServiceReference1.Employee GetEmployeeDetailResult;
        
        public GetEmployeeDetailResponseBody() {
        }
        
        public GetEmployeeDetailResponseBody(Jquery.ServiceReference1.Employee GetEmployeeDetailResult) {
            this.GetEmployeeDetailResult = GetEmployeeDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface samplewebserviceSoapChannel : Jquery.ServiceReference1.samplewebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class samplewebserviceSoapClient : System.ServiceModel.ClientBase<Jquery.ServiceReference1.samplewebserviceSoap>, Jquery.ServiceReference1.samplewebserviceSoap {
        
        public samplewebserviceSoapClient() {
        }
        
        public samplewebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public samplewebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public samplewebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public samplewebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Jquery.ServiceReference1.GetEmployeeDetailResponse Jquery.ServiceReference1.samplewebserviceSoap.GetEmployeeDetail(Jquery.ServiceReference1.GetEmployeeDetailRequest request) {
            return base.Channel.GetEmployeeDetail(request);
        }
        
        public Jquery.ServiceReference1.Employee GetEmployeeDetail() {
            Jquery.ServiceReference1.GetEmployeeDetailRequest inValue = new Jquery.ServiceReference1.GetEmployeeDetailRequest();
            inValue.Body = new Jquery.ServiceReference1.GetEmployeeDetailRequestBody();
            Jquery.ServiceReference1.GetEmployeeDetailResponse retVal = ((Jquery.ServiceReference1.samplewebserviceSoap)(this)).GetEmployeeDetail(inValue);
            return retVal.Body.GetEmployeeDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Jquery.ServiceReference1.GetEmployeeDetailResponse> Jquery.ServiceReference1.samplewebserviceSoap.GetEmployeeDetailAsync(Jquery.ServiceReference1.GetEmployeeDetailRequest request) {
            return base.Channel.GetEmployeeDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Jquery.ServiceReference1.GetEmployeeDetailResponse> GetEmployeeDetailAsync() {
            Jquery.ServiceReference1.GetEmployeeDetailRequest inValue = new Jquery.ServiceReference1.GetEmployeeDetailRequest();
            inValue.Body = new Jquery.ServiceReference1.GetEmployeeDetailRequestBody();
            return ((Jquery.ServiceReference1.samplewebserviceSoap)(this)).GetEmployeeDetailAsync(inValue);
        }
    }
}
