//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD_RENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int MemberShipID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateJoined { get; set; }
    
        public virtual MembershipType MembershipType { get; set; }
    }
}
